# Generated by Django 2.2.6 on 2020-05-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_block',
            name='image',
            field=models.ImageField(default='dsfs', upload_to='images/'),
            preserve_default=False,
        ),
    ]
