# Generated by Django 2.2.6 on 2020-05-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_block_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_block',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
