# Generated by Django 2.2.6 on 2020-05-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_address_list_contact_block_email_list_phone_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_list',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='contact_block',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='Contact', to='home.Address_list', verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='contact_block',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='Contact', to='home.Email_list', verbose_name='Емайлы'),
        ),
        migrations.AlterField(
            model_name='contact_block',
            name='phones',
            field=models.ManyToManyField(blank=True, related_name='Contact', to='home.Phone_list', verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='email_list',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Емаил'),
        ),
        migrations.AlterField(
            model_name='home_block',
            name='body',
            field=models.CharField(max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='home_block',
            name='first_button',
            field=models.CharField(max_length=15, verbose_name='Название первой кнопки'),
        ),
        migrations.AlterField(
            model_name='home_block',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фоновая картинка'),
        ),
        migrations.AlterField(
            model_name='home_block',
            name='second_button',
            field=models.CharField(max_length=15, verbose_name='Название второй кнопки'),
        ),
        migrations.AlterField(
            model_name='home_block',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='phone_list',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='portfolio_block',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='portfolio_block',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service_block',
            name='body',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service_block',
            name='first_button',
            field=models.CharField(max_length=15, verbose_name='Название кнопки'),
        ),
        migrations.AlterField(
            model_name='service_block',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='service_block',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='social_networks',
            name='icon',
            field=models.CharField(max_length=20, verbose_name='Иконка (fa fa icon)'),
        ),
        migrations.AlterField(
            model_name='social_networks',
            name='url',
            field=models.CharField(max_length=50, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='welcome_block',
            name='about_title',
            field=models.CharField(max_length=50, verbose_name='Надпись под заголовком'),
        ),
        migrations.AlterField(
            model_name='welcome_block',
            name='body',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='welcome_block',
            name='first_button',
            field=models.CharField(max_length=15, verbose_name='Название первой кнопки'),
        ),
        migrations.AlterField(
            model_name='welcome_block',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='welcome_block',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='why_us',
            name='body',
            field=models.CharField(max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='why_us',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='Иконка (fa fa icon))'),
        ),
        migrations.AlterField(
            model_name='why_us',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
