# Generated by Django 2.2.6 on 2020-05-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200523_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address_list',
            options={'verbose_name': 'Список адресов', 'verbose_name_plural': 'Информация со списком адресов'},
        ),
        migrations.AlterModelOptions(
            name='contact_block',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': '7.Информация с последнего блока(Контакты)'},
        ),
        migrations.AlterModelOptions(
            name='email_list',
            options={'verbose_name': 'Список почт', 'verbose_name_plural': 'Информация со списком электронных почт'},
        ),
        migrations.AlterModelOptions(
            name='home_block',
            options={'verbose_name': 'Домашний блок', 'verbose_name_plural': '1.Информация с первого блока(домашнего)'},
        ),
        migrations.AlterModelOptions(
            name='phone_list',
            options={'verbose_name': 'Список номеров', 'verbose_name_plural': 'Информация со списком номеров'},
        ),
        migrations.AlterModelOptions(
            name='portfolio_block',
            options={'verbose_name': 'Портфолио', 'verbose_name_plural': '5.Информация с пятого блока(Портфолио)'},
        ),
        migrations.AlterModelOptions(
            name='service_block',
            options={'verbose_name': 'Наш сервис', 'verbose_name_plural': '4.Информация с четвёртого блока(Наше сервис)'},
        ),
        migrations.AlterModelOptions(
            name='social_networks',
            options={'verbose_name': 'Социальные сети', 'verbose_name_plural': '6.Информация с шестого блока(Социальные сети)'},
        ),
        migrations.AlterModelOptions(
            name='welcome_block',
            options={'verbose_name': 'Приветствующий блок', 'verbose_name_plural': '2.Информация с второго блока(Добро пожаловать)'},
        ),
        migrations.AlterModelOptions(
            name='why_us',
            options={'verbose_name': 'Почему мы', 'verbose_name_plural': '3.Информация с третьего блока(Почему мы)'},
        ),
        migrations.AlterField(
            model_name='contact_block',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='Address_list', to='home.Address_list', verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='contact_block',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='Email_list', to='home.Email_list', verbose_name='Емайлы'),
        ),
        migrations.AlterField(
            model_name='contact_block',
            name='phones',
            field=models.ManyToManyField(blank=True, related_name='Phone_list', to='home.Phone_list', verbose_name='Телефоны'),
        ),
    ]
