# Generated by Django 2.2.6 on 2020-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200525_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_block',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service_block',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='welcome_block',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='why_us',
            name='body',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='why_us',
            name='icon',
            field=models.CharField(max_length=20, verbose_name='Иконка (fa fa icon))'),
        ),
    ]
